services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
        - '3000:3000'

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - '8080:80'
    depends_on:
        - server

