### login user
POST {{api}}/auth/login
Content-Type: application/json

{
"email": "kellysmith@email.com",
"password": "123456"
}

### login user2
POST {{api}}/login
Content-Type: application/json

{
"email": "kelly2@email.com",
"password": "123456"
}

### login with wrong password
POST {{api}}/login
Content-Type: application/json

{
"username": "kellysmith",
"password": "1234567"
}

### refresh token
POST {{api}}/auth/refresh-token
