### login user
POST {{api}}/auth/login
Content-Type: application/json

{
"email": "kellysmith@email.com",
"password": "12345678"
}

### login user2
POST {{api}}/auth/login
Content-Type: application/json

{
"email": "kelly2@email.com",
"password": "12345678"
}

### login with user3
POST {{api}}/auth/login
Content-Type: application/json

{
"email": "dog@email.com",
"password": "12345678"
}

### refresh token
GET {{api}}/auth/refresh-token
