### signup user
POST {{api}}/signup
Content-Type: application/json

{
"username": "kellysmith",
"email": "kellysmith@email.com",
"password": "123456"
}

### signup user2
POST {{api}}/signup
Content-Type: application/json

{
"username": "kelly2",
"email": "kelly2@email.com",
"password": "123456"
}

### signup user3 fail
POST {{api}}/signup
Content-Type: application/json

{
"username": "janedoe",
"email": "janedoe@email.com"
}
