### signup user
POST {{api}}/auth/signup
Content-Type: application/json

{
  "username": "kellysmith",
  "name": "Kelly Smith",
  "email": "kellysmith@email.com",
  "password": "12345678"
}

### signup user2
POST {{api}}/auth/signup
Content-Type: application/json

{
  "username": "kelly2",
  "name": "Kelly 2",
  "email": "kelly2@email.com",
  "password": "12345678"
}

### signup user3 fail
POST {{api}}/auth/signup
Content-Type: application/json

{
"username": "janedoe",
"email": "janedoe@email.com"
}
