### get comments
GET {{api}}/posts/67358b53b86a90543ff5aa81/comments

### comment post
POST {{api}}/posts/67358b53b86a90543ff5aa81/comments
Content-Type: application/json

{
  "text": "This is a comment2"
}