### Create post (protected)
POST {{api}}/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTczMjE3MDI1NCwiZXhwIjoxNzMyMTcxMTU0fQ.aq0Ve30MFgbJLq7modnzIhRTzRcPESXDuR8FdV-1hMY

{
  "text": "bark bark bark"
}

### Create post2 (protected)
POST {{api}}/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczMTk4NTUyMiwiZXhwIjoxNzMxOTg2NDIyfQ.xyPwhGK4XX6aGrzFU6zXj0d61M96ty7UeVIP8wBP4TI
Content-Type: application/json

{
    "text": "This is a post2"
}

### Create Comment (protected)
POST {{api}}/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTczMjE4MDU0NSwiZXhwIjoxNzMyMTgxNDQ1fQ.RpJvRWjs13arvlSz2AfD7PGfWK9Ph28cJFQJiDC8q-Y
Content-Type: application/json

{
    "text": "comment from dog 4"
}