### login user
POST {{api}}/users/login
Content-Type: application/json

{
"username": "kelliesmith",
"password": "123456"
}

### login user2
POST {{api}}/users/login
Content-Type: application/json

{
"username": "kelly2",
"password": "123456"
}

### login with wrong password
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
"username": "kelliesmith",
"password": "1234567"
}