### signup user
POST {{api}}/users/signup
Content-Type: application/json

{
"username": "kelliesmith",
"name": "Kellie Smith",
"email": "kelliesmith@email.com",
"password": "123456"
}

### signup user2
POST {{api}}/users/signup
Content-Type: application/json

{
"username": "kelly2",
"name": "Kelly2",
"email": "kelly2@email.com",
"password": "123456"
}

### signup user3 fail
POST {{api}}/users/signup
Content-Type: application/json

{
"username": "janedoe",
"email": "janedoe@email.com"
}
