### Get all users
GET {{api}}/users

### follow/unfollow user
PUT {{api}}/users/follow/673536107029211c0f788f08

### Test follow self
PUT {{api}}/users/follow/6735360c7029211c0f788f05

### Update user
PUT {{api}}/users/me/profile
Content-Type: application/json

{
"name": "Kelly Smith 3"
}

### Get user profile by username
GET {{api}}/users/kelliesmith